### ISSUE TITLE
[Tracking Issue] Have the ink! stack support `pallet-revive`

### ISSUE THREAD

**Issue by cmichi** [use-ink/ink-alliance#9]
The idea is to have the next major version of ink! and `cargo-contract` be `pallet-revive`/PolkaVM exclusive. So no more support for Wasm or `pallet-contracts`.

We can still backport fixes (or even features) to old releases if needed, but it's a significant decrease in workload if we only have to maintain one execution platform.

## `ink` 
- [ ] Adapt CI to compile integration tests for PVM 
- [ ] Adapt CI run E2E tests against `pallet-revive` on `substrate-contracts-node`
- [ ] Migrate + remove anything Wasm/`pallet-contracts`-specific from the code

## `cargo-contract`
- [ ] Add support for deploying to `pallet-revive`
- [ ] Adapt CI
- [ ] Migrate + remove anything Wasm/`pallet-contracts`-specific from the code

## `ink-docs`
- [ ] Create new subpage for next major ink! release
- [ ] Migrate existing docs on `pallet-contracts` to `pallet-revive`
- [ ] Add page explaining PVM/RISC-V

## `substrate-contracts-node`
- [x] Add `pallet-revive` in addition to `pallet-contracts` (https://github.com/use-ink/substrate-contracts-node/pull/1)
- [ ] Remove `pallet-contracts` and issue a new release

##  Create Issues in external repos to support `pallet-revive` instead of `pallet-contracts`
- [ ] PAPI
- [ ] `polkadot-js/api` and `polkadot-js/contracts`
- [ ] ink!athon
